backend:
  name: github
  repo: pgcsoluciones/regalos-prince
  branch: main
  base_url: https://regalos.grupoprince.com
  auth_endpoint: api/auth # Sin barra inicial para evitar conflictos de rutas
  
local_backend: true # Permite pruebas locales si fuera necesario

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "configuracion"
    label: "Configuración General"
    files:
      - file: "content/site/home.json"
        label: "Home"
        name: "home"
        fields:
          - {label: "Título", name: "title", widget: "string"}
