backend:
  name: github
  repo: pgcsoluciones/regalos-prince
  branch: main
  base_url: https://regalos.grupoprince.com
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Paginas"
    files:
      - file: "content/site/home.json"
        label: "Home"
        name: "home"
        fields:
          - {label: "Titulo", name: "title", widget: "string"}
