backend:
  name: github
  repo: pgcsoluciones/regalos-prince
  branch: main
  base_url: https://regalos.grupoprince.com
  auth_endpoint: api/auth

publish_mode: editorial_workflow

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Secciones del Sitio"
    format: "json"
    files:
      - file: "content/site/home.json"
        label: "Inicio"
        name: "home"
        fields:
          - {label: "TÃ­tulo", name: "title", widget: "string"}
